// <auto-generated />
using CompanyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyApi.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyApi.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Exchange = "NASDAQ",
                            Isin = "US0378331005",
                            Name = "Apple Inc.",
                            Ticker = "AAPL",
                            Website = "http://www.apple.com"
                        },
                        new
                        {
                            Id = 2,
                            Exchange = "Pink Sheets",
                            Isin = "US1104193065",
                            Name = "British Airways Plc",
                            Ticker = "BAIRY"
                        },
                        new
                        {
                            Id = 3,
                            Exchange = "Euronext Amsterdam",
                            Isin = "NL0000009165",
                            Name = "Heineken NV",
                            Ticker = "HEIA"
                        },
                        new
                        {
                            Id = 4,
                            Exchange = "Tokyo Stock Exchange",
                            Isin = "JP3866800000",
                            Name = "Panasonic Corp",
                            Ticker = "6752",
                            Website = "http://www.panasonic.co.jp"
                        },
                        new
                        {
                            Id = 5,
                            Exchange = "Deutsche Börse",
                            Isin = "DE000PAH0038",
                            Name = "Porsche Automobil",
                            Ticker = "PAH3",
                            Website = "https://www.porsche.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
