/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCompanyDto {
  exchange: string;
  isin: string;
  name: string;
  ticker: string;
  website?: string | null;
}
