/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCompanyDto {
  exchange?: string | null;
  isin?: string | null;
  name?: string | null;
  ticker?: string | null;
  website?: string | null;
}
