version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "VeryStr0ng!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10   

  api:
    build:
      context: .
      dockerfile: CompanyApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Enable dev mode for swagger
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CompanyDb;User Id=sa;Password=VeryStr0ng!Passw0rd;TrustServerCertificate=True
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./company-frontend
      dockerfile: Dockerfile
    ports:
      - "4300:4200"
      - "4301:4201"
    depends_on:
      - api

